
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.profile" ]; then
        . "$HOME/.profile"
    fi
fi

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PROJECT_HOME=$HOME/Development/python
source /usr/local/bin/virtualenvwrapper.sh