#!/bin/bash

# Hello Messsage --------------------------------------------------
echo -e "Kernel Information: " `uname -smr`
echo -e "`bash --version`"
echo -ne "Uptime: "; uptime
echo -ne "Server time is: "; date

export TERM=xterm-256color

export EDITOR='emacs -nw -q'

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PROJECT_HOME=$HOME/Development/python
source /usr/local/bin/virtualenvwrapper.sh

source ~/.bash_aliases
