#!/bin/bash

# https://github.com/mathiasbynens/dotfiles/blob/master/.aliases
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
    colorflag="--color"
else # OS X `ls`
    colorflag="-G"
fi

alias emacs="emacs -nw"
alias ls='ls -aF ${colorflag}'

alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias df='df -h'

# Load server aliases; alias server="ssh user@server"
if [ -f "~/.server_aliases" ]; then
  . ~/.server_aliases
fi

alias mkve="mkvirtualenv"
alias mkve26="mkvirtualenv -p /usr/bin/python2.6"
alias mkve3="mkvirtualenv -p /usr/bin/python3"