#!/bin/bash
export TERM=xterm-256color

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PROJECT_HOME=$HOME/Development/python
source /usr/local/bin/virtualenvwrapper.sh
