#!/bin/bash

alias emacs="emacs -nw"
alias ls='ls -aF'

alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias df='df -h'

# Load server aliases; alias server="ssh user@server"
if [ -f "~/.server_aliases" ]; then
  . ~/.server_aliases
fi

alias mkve="mkvirtualenv"
alias mkve26="mkvirtualenv -p /usr/bin/python2.6"
alias mkve3="mkvirtualenv -p /usr/bin/python3"