(add-to-list 'load-path "~/.emacs.d/vendor")

(load "jsoa/defuns")
(load "jsoa/theme")
(load "jsoa/env")
(load "jsoa/global")
(load "jsoa/bindings")
(load "jsoa/grep")
(load "jsoa/diff")

(load "jsoa/nxhtml")

(vendor 'python-mode)
(vendor 'python-pep8)
(vendor 'python-pylint)
(vendor 'pylookup)
(vendor 'virtualenv)
(vendor 'coffee-mode)
(vendor 'js2-mode)
(vendor 'jade-mode)
(vendor 'scss-mode)
(vendor 'yasnippet)
(vendor 'json-mode)
(vendor 'magit)
(vendor 'markdown-mode)
(vendor 'textmate)
(vendor 'auto-complete)
(vendor 'smooth-scroll)
(vendor 'fill-column-indicator)
(vendor 'smart-tab)
(vendor 'findr)
(vendor 'multiple-cursors)
(vendor 'expand-region)

(vendor 'erc)