#! /bin/bash

sudo easy_install pip
# sudo pip install --upgrade pip
sudo pip install -r $HOME/Development/python/reqs.txt

# Some of these lines are also in bash_profile
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
source /usr/local/bin/virtualenvwrapper.sh

# Python virtualenvs
mkvirtualenv -p /usr/bin/python2.6 py26
# python 2.7 is currently default
# mkvirtualenv -p /usr/bin/python2.7 py27
mkvirtualenv -p /usr/bin/python3 py3

# Django virtualenvs
mkvirtualenv dj14
mkvirtualenv dj13
mkvirtualenv dj12

workon dj14
pip install django==1.4

workon dj13
pip install django==1.3.1

workon dj12
pip install django==1.2.7
